program: exp/run.py
method: grid
metric:
  name: val_acc
  goal: maximize
parameters:
  model:
    value: BayesBundleSheaf
  d:
    value: 2
  add_lp:
    value: 0
  add_hp:
    value: 1
  dataset:
    value: cora
  layers:
    value: 2
  hidden_channels:
    value: 32
  weight_decay:
    value: 0.0008917038645
  sheaf_decay:
    value: 8.229945816e-05
  input_dropout:
    value: 0.8
  dropout:
    value: 0.3
  lr:
    value: 0.01
  epochs:
    value: 500
  early_stopping:
    value: 200
  folds:
    value: 10
  orth:
    value: householder
  seed:
    values:
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 8
    - 9
    - 10
    - 11
    - 12
    - 13
    - 14
    - 15
    - 16
    - 17
    - 18
    - 19
    - 20
    - 21
    - 22
    - 23
    - 24
    - 25
    - 26
    - 27
    - 28
    - 29
  save_dir:
    value: saved_models
  left_weights:
    value: true
  right_weights:
    value: true
  use_act:
    value: true
  normalised:
    value: true
  edge_weights:
    value: true
  use_kl:
    value: true
  sheaf_use_deg:
    value: false
  permute_masks:
    value: true
  num_ensemble:
    value: 3
command:
- ${env}
- python3
- ${program}
- ${args}
- --save_model
- --entity=${ENTITY}
